name: Remove Feature Containers

on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  remove-feature-containers:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Get merged PR branch name
      id: pr-info
      run: |
        BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }})
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: List and Remove Feature Container
      env:
        BRANCH_NAME: ${{ env.BRANCH_NAME }}
      run: |
        if [[ "$BRANCH_NAME" == feature-* ]]; then
          # List running tasks in the feature cluster
          TASKS=$(aws ecs list-tasks --cluster feature --query 'taskArns' --output text)
          
          if [ -z "$TASKS" ]; then
            echo "No running tasks found."
          else
            for TASK in $TASKS; do
              # Describe the task to get the container image
              CONTAINER_IMAGE=$(aws ecs describe-tasks --cluster feature --tasks $TASK --query 'tasks[0].containers[0].image' --output text)
              
              if [[ $CONTAINER_IMAGE == 975622744795.dkr.ecr.us-east-1.amazonaws.com/$BRANCH_NAME* ]]; then
                # Stop the task if it's the feature container
                aws ecs stop-task --cluster feature --task $TASK
                echo "Stopped task $TASK with image $CONTAINER_IMAGE"
              fi
            done
          fi
        else
          echo "No feature branch found."
        fi
